export enum BaseToken {
  DB_CONTEXT = 'DB_CONTEXT',
  DATA_SOURCE = 'DATA_SOURCE',
  EVENT_DISPATCHER = 'EVENT_DISPATCHER',
  INTEGRATION_SERVICE = 'INTEGRATION_SERVICE',
}

export enum QueryToken {
  GET_MOVIE_SESSION = 'GET_MOVIE_SESSION',
  LIST_MOVIE_SESSIONS = 'LIST_MOVIE_SESSIONS',
}

export enum CommandToken {
  CANCEL_MOVIE_SESSION = 'CANCEL_MOVIE_SESSION',
  CANCEL_TICKET_BINDING = 'CANCEL_TICKET_BINDING',
  BIND_TICKET_TO_CUSTOMER = 'BIND_TICKET_TO_CUSTOMER',
}

export enum ServiceToken {
  MOVIE_PROVIDER = 'MOVIE_PROVIDER',
}
